// src/ui/solid/HelpV2/HelpV2.solid.tsx
/**
 * Help screen (V2) with tabbed navigation.
 *
 * SolidJS + OpenTUI port of src/components/HelpV2/HelpV2.tsx.
 *
 * Note: This component uses several hooks from the React codebase
 * (useExitOnCtrlCDWithKeybindings, useKeybinding, useShortcutDisplay,
 *  useTerminalSize, useIsInsideModal) and components (Tabs, Tab, Commands,
 *  Link, Pane). These are referenced but would need Solid equivalents.
 * The presentational layout is fully ported.
 */

import { Show, For } from 'solid-js'
import type { JSX } from '@opentui/solid'
import {
  builtInCommandNames,
  type Command,
  type CommandResultDisplay,
} from '../../../commands.js'
import { Pane } from '../design-system/Pane.solid.js'
import { General } from './General.solid.js'

interface HelpV2Props {
  onClose: (
    result?: string,
    options?: { display?: CommandResultDisplay },
  ) => void
  commands: Command[]
  /** Terminal rows for sizing. */
  rows?: number
  /** Terminal columns for sizing. */
  columns?: number
  /** Whether rendered inside a modal slot. */
  insideModal?: boolean
  /** The exit state for ctrl+c/d display. */
  exitState?: { pending: boolean; keyName: string }
  /** The dismiss shortcut text. */
  dismissShortcut?: string
}

export function HelpV2(props: HelpV2Props) {
  const rows = () => props.rows ?? 24
  const columns = () => props.columns ?? 80
  const maxHeight = () => Math.floor(rows() / 2)
  const insideModal = () => props.insideModal ?? false
  const exitState = () => props.exitState ?? { pending: false, keyName: 'ctrl+c' }
  const dismissShortcut = () => props.dismissShortcut ?? 'esc'

  const close = () =>
    props.onClose('Help dialog dismissed', { display: 'system' })

  const builtinNames = () => builtInCommandNames()

  const builtinCommands = () =>
    props.commands.filter(
      (cmd) => builtinNames().has(cmd.name) && !cmd.isHidden,
    )

  const customCommands = () =>
    props.commands.filter(
      (cmd) => !builtinNames().has(cmd.name) && !cmd.isHidden,
    )

  const height = () => (insideModal() ? undefined : maxHeight())

  return (
    <box flexDirection="column" height={height()}>
      <Pane color="professionalBlue">
        {/* Tabs would go here -- using a simplified layout until Tabs is ported */}
        <box flexDirection="column">
          <text fg="professionalBlue">
            <b>{`Noble Base Code v${MACRO.VERSION}`}</b>
          </text>

          {/* General tab content */}
          <General />

          {/* Commands info placeholder */}
          <Show when={builtinCommands().length > 0}>
            <box flexDirection="column" marginTop={1}>
              <text><b>Commands</b></text>
              <text dimmed>
                {builtinCommands().length} built-in commands,{' '}
                {customCommands().length} custom commands
              </text>
            </box>
          </Show>
        </box>

        <box marginTop={1}>
          <text>
            For more help:{' '}
            <text fg="blue"><u>https://code.claude.com/docs/en/overview</u></text>
          </text>
        </box>

        <box marginTop={1}>
          <text dimmed>
            <Show
              when={!exitState().pending}
              fallback={<>Press {exitState().keyName} again to exit</>}
            >
              <i>{dismissShortcut()} to cancel</i>
            </Show>
          </text>
        </box>
      </Pane>
    </box>
  )
}

// src/components/HelpV2/HelpV2.tsx
import { c as _c } from "react/compiler-runtime";
import * as React from 'react';
import { useExitOnCtrlCDWithKeybindings } from 'src/hooks/useExitOnCtrlCDWithKeybindings.js';
import { useShortcutDisplay } from 'src/keybindings/useShortcutDisplay.js';
import { builtInCommandNames, type Command, type CommandResultDisplay, INTERNAL_ONLY_COMMANDS } from '../../commands.js';
import { useIsInsideModal } from '../../context/modalContext.js';
import { useTerminalSize } from '../../hooks/useTerminalSize.js';
import { Box, Link, Text } from '../../ink.js';
import { useKeybinding } from '../../keybindings/useKeybinding.js';
import { Pane } from '../design-system/Pane.js';
import { Tab, Tabs } from '../design-system/Tabs.js';
import { Commands } from './Commands.js';
import { General } from './General.js';
type Props = {
  onClose: (result?: string, options?: {
    display?: CommandResultDisplay;
  }) => void;
  commands: Command[];
};
export function HelpV2(t0) {
  const $ = _c(44);
  const {
    onClose,
    commands
  } = t0;
  const {
    rows,
    columns
  } = useTerminalSize();
  const maxHeight = Math.floor(rows / 2);
  const insideModal = useIsInsideModal();
  let t1;
  if ($[0] !== onClose) {
    t1 = () => onClose("Help dialog dismissed", {
      display: "system"
    });
    $[0] = onClose;
    $[1] = t1;
  } else {
    t1 = $[1];
  }
  const close = t1;
  let t2;
  if ($[2] === Symbol.for("react.memo_cache_sentinel")) {
    t2 = {
      context: "Help"
    };
    $[2] = t2;
  } else {
    t2 = $[2];
  }
  useKeybinding("help:dismiss", close, t2);
  const exitState = useExitOnCtrlCDWithKeybindings(close);
  const dismissShortcut = useShortcutDisplay("help:dismiss", "Help", "esc");
  let antOnlyCommands;
  let builtinCommands;
  let t3;
  if ($[3] !== commands) {
    const builtinNames = builtInCommandNames();
    builtinCommands = commands.filter(cmd => builtinNames.has(cmd.name) && !cmd.isHidden);
    let t4;
    if ($[7] === Symbol.for("react.memo_cache_sentinel")) {
      t4 = [];
      $[7] = t4;
    } else {
      t4 = $[7];
    }
    antOnlyCommands = t4;
    t3 = commands.filter(cmd_2 => !builtinNames.has(cmd_2.name) && !cmd_2.isHidden);
    $[3] = commands;
    $[4] = antOnlyCommands;
    $[5] = builtinCommands;
    $[6] = t3;
  } else {
    antOnlyCommands = $[4];
    builtinCommands = $[5];
    t3 = $[6];
  }
  const customCommands = t3;
  let t4;
  if ($[8] === Symbol.for("react.memo_cache_sentinel")) {
    t4 = <Tab key="general" title="general"><General /></Tab>;
    $[8] = t4;
  } else {
    t4 = $[8];
  }
  let tabs;
  if ($[9] !== antOnlyCommands || $[10] !== builtinCommands || $[11] !== close || $[12] !== columns || $[13] !== customCommands || $[14] !== maxHeight) {
    tabs = [t4];
    let t5;
    if ($[16] !== builtinCommands || $[17] !== close || $[18] !== columns || $[19] !== maxHeight) {
      t5 = <Tab key="commands" title="commands"><Commands commands={builtinCommands} maxHeight={maxHeight} columns={columns} title="Browse default commands:" onCancel={close} /></Tab>;
      $[16] = builtinCommands;
      $[17] = close;
      $[18] = columns;
      $[19] = maxHeight;
      $[20] = t5;
    } else {
      t5 = $[20];
    }
    tabs.push(t5);
    let t6;
    if ($[21] !== close || $[22] !== columns || $[23] !== customCommands || $[24] !== maxHeight) {
      t6 = <Tab key="custom" title="custom-commands"><Commands commands={customCommands} maxHeight={maxHeight} columns={columns} title="Browse custom commands:" emptyMessage="No custom commands found" onCancel={close} /></Tab>;
      $[21] = close;
      $[22] = columns;
      $[23] = customCommands;
      $[24] = maxHeight;
      $[25] = t6;
    } else {
      t6 = $[25];
    }
    tabs.push(t6);
    if (false && antOnlyCommands.length > 0) {
      let t7;
      if ($[26] !== antOnlyCommands || $[27] !== close || $[28] !== columns || $[29] !== maxHeight) {
        t7 = <Tab key="ant-only" title="[ant-only]"><Commands commands={antOnlyCommands} maxHeight={maxHeight} columns={columns} title="Browse ant-only commands:" onCancel={close} /></Tab>;
        $[26] = antOnlyCommands;
        $[27] = close;
        $[28] = columns;
        $[29] = maxHeight;
        $[30] = t7;
      } else {
        t7 = $[30];
      }
      tabs.push(t7);
    }
    $[9] = antOnlyCommands;
    $[10] = builtinCommands;
    $[11] = close;
    $[12] = columns;
    $[13] = customCommands;
    $[14] = maxHeight;
    $[15] = tabs;
  } else {
    tabs = $[15];
  }
  const t5 = insideModal ? undefined : maxHeight;
  let t6;
  if ($[31] !== tabs) {
    t6 = <Tabs title={false ? "/help" : `Noble Base Code v${MACRO.VERSION}`} color="professionalBlue" defaultTab="general">{tabs}</Tabs>;
    $[31] = tabs;
    $[32] = t6;
  } else {
    t6 = $[32];
  }
  let t7;
  if ($[33] === Symbol.for("react.memo_cache_sentinel")) {
    t7 = <Box marginTop={1}><Text>For more help:{" "}<Link url="https://code.claude.com/docs/en/overview" /></Text></Box>;
    $[33] = t7;
  } else {
    t7 = $[33];
  }
  let t8;
  if ($[34] !== dismissShortcut || $[35] !== exitState.keyName || $[36] !== exitState.pending) {
    t8 = <Box marginTop={1}><Text dimColor={true}>{exitState.pending ? <>Press {exitState.keyName} again to exit</> : <Text italic={true}>{dismissShortcut} to cancel</Text>}</Text></Box>;
    $[34] = dismissShortcut;
    $[35] = exitState.keyName;
    $[36] = exitState.pending;
    $[37] = t8;
  } else {
    t8 = $[37];
  }
  let t9;
  if ($[38] !== t6 || $[39] !== t8) {
    t9 = <Pane color="professionalBlue">{t6}{t7}{t8}</Pane>;
    $[38] = t6;
    $[39] = t8;
    $[40] = t9;
  } else {
    t9 = $[40];
  }
  let t10;
  if ($[41] !== t5 || $[42] !== t9) {
    t10 = <Box flexDirection="column" height={t5}>{t9}</Box>;
    $[41] = t5;
    $[42] = t9;
    $[43] = t10;
  } else {
    t10 = $[43];
  }
  return t10;
}
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJuYW1lcyI6WyJSZWFjdCIsInVzZUV4aXRPbkN0cmxDRFdpdGhLZXliaW5kaW5ncyIsInVzZVNob3J0Y3V0RGlzcGxheSIsImJ1aWx0SW5Db21tYW5kTmFtZXMiLCJDb21tYW5kIiwiQ29tbWFuZFJlc3VsdERpc3BsYXkiLCJJTlRFUk5BTF9PTkxZX0NPTU1BTkRTIiwidXNlSXNJbnNpZGVNb2RhbCIsInVzZVRlcm1pbmFsU2l6ZSIsIkJveCIsIkxpbmsiLCJUZXh0IiwidXNlS2V5YmluZGluZyIsIlBhbmUiLCJUYWIiLCJUYWJzIiwiQ29tbWFuZHMiLCJHZW5lcmFsIiwiUHJvcHMiLCJvbkNsb3NlIiwicmVzdWx0Iiwib3B0aW9ucyIsImRpc3BsYXkiLCJjb21tYW5kcyIsIkhlbHBWMiIsInQwIiwiJCIsIl9jIiwicm93cyIsImNvbHVtbnMiLCJtYXhIZWlnaHQiLCJNYXRoIiwiZmxvb3IiLCJpbnNpZGVNb2RhbCIsInQxIiwiY2xvc2UiLCJ0MiIsIlN5bWJvbCIsImZvciIsImNvbnRleHQiLCJleGl0U3RhdGUiLCJkaXNtaXNzU2hvcnRjdXQiLCJhbnRPbmx5Q29tbWFuZHMiLCJidWlsdGluQ29tbWFuZHMiLCJ0MyIsImJ1aWx0aW5OYW1lcyIsImZpbHRlciIsImNtZCIsImhhcyIsIm5hbWUiLCJpc0hpZGRlbiIsInQ0IiwiY21kXzIiLCJjdXN0b21Db21tYW5kcyIsInRhYnMiLCJ0NSIsInB1c2giLCJ0NiIsImxlbmd0aCIsInQ3IiwidW5kZWZpbmVkIiwiTUFDUk8iLCJWRVJTSU9OIiwidDgiLCJrZXlOYW1lIiwicGVuZGluZyIsInQ5IiwidDEwIl0sInNvdXJjZXMiOlsiSGVscFYyLnRzeCJdLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgKiBhcyBSZWFjdCBmcm9tICdyZWFjdCdcbmltcG9ydCB7IHVzZUV4aXRPbkN0cmxDRFdpdGhLZXliaW5kaW5ncyB9IGZyb20gJ3NyYy9ob29rcy91c2VFeGl0T25DdHJsQ0RXaXRoS2V5YmluZGluZ3MuanMnXG5pbXBvcnQgeyB1c2VTaG9ydGN1dERpc3BsYXkgfSBmcm9tICdzcmMva2V5YmluZGluZ3MvdXNlU2hvcnRjdXREaXNwbGF5LmpzJ1xuaW1wb3J0IHtcbiAgYnVpbHRJbkNvbW1hbmROYW1lcyxcbiAgdHlwZSBDb21tYW5kLFxuICB0eXBlIENvbW1hbmRSZXN1bHREaXNwbGF5LFxuICBJTlRFUk5BTF9PTkxZX0NPTU1BTkRTLFxufSBmcm9tICcuLi8uLi9jb21tYW5kcy5qcydcbmltcG9ydCB7IHVzZUlzSW5zaWRlTW9kYWwgfSBmcm9tICcuLi8uLi9jb250ZXh0L21vZGFsQ29udGV4dC5qcydcbmltcG9ydCB7IHVzZVRlcm1pbmFsU2l6ZSB9IGZyb20gJy4uLy4uL2hvb2tzL3VzZVRlcm1pbmFsU2l6ZS5qcydcbmltcG9ydCB7IEJveCwgTGluaywgVGV4dCB9IGZyb20gJy4uLy4uL2luay5qcydcbmltcG9ydCB7IHVzZUtleWJpbmRpbmcgfSBmcm9tICcuLi8uLi9rZXliaW5kaW5ncy91c2VLZXliaW5kaW5nLmpzJ1xuaW1wb3J0IHsgUGFuZSB9IGZyb20gJy4uL2Rlc2lnbi1zeXN0ZW0vUGFuZS5qcydcbmltcG9ydCB7IFRhYiwgVGFicyB9IGZyb20gJy4uL2Rlc2lnbi1zeXN0ZW0vVGFicy5qcydcbmltcG9ydCB7IENvbW1hbmRzIH0gZnJvbSAnLi9Db21tYW5kcy5qcydcbmltcG9ydCB7IEdlbmVyYWwgfSBmcm9tICcuL0dlbmVyYWwuanMnXG5cbnR5cGUgUHJvcHMgPSB7XG4gIG9uQ2xvc2U6IChcbiAgICByZXN1bHQ/OiBzdHJpbmcsXG4gICAgb3B0aW9ucz86IHsgZGlzcGxheT86IENvbW1hbmRSZXN1bHREaXNwbGF5IH0sXG4gICkgPT4gdm9pZFxuICBjb21tYW5kczogQ29tbWFuZFtdXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBIZWxwVjIoeyBvbkNsb3NlLCBjb21tYW5kcyB9OiBQcm9wcyk6IFJlYWN0LlJlYWN0Tm9kZSB7XG4gIGNvbnN0IHsgcm93cywgY29sdW1ucyB9ID0gdXNlVGVybWluYWxTaXplKClcbiAgY29uc3QgbWF4SGVpZ2h0ID0gTWF0aC5mbG9vcihyb3dzIC8gMilcbiAgLy8gSW5zaWRlIHRoZSBtb2RhbCBzbG90LCBGdWxsc2NyZWVuTGF5b3V0IGFscmVhZHkgY2FwcyBoZWlnaHQgYW5kIFBhbmUvVGFic1xuICAvLyB1c2UgZmxleFNocmluaz0wIChzZWUgIzIzNTkyKSDigJQgb3VyIG93biBoZWlnaHQ9IGNvbnN0cmFpbnQgd291bGQgY2xpcCB0aGVcbiAgLy8gZm9vdGVyIHNpbmNlIFRhYnMgd29uJ3Qgc2hyaW5rIHRvIGZpdC4gTGV0IHRoZSBtb2RhbCBzbG90IGhhbmRsZSBzaXppbmcuXG4gIGNvbnN0IGluc2lkZU1vZGFsID0gdXNlSXNJbnNpZGVNb2RhbCgpXG5cbiAgY29uc3QgY2xvc2UgPSAoKSA9PiBvbkNsb3NlKCdIZWxwIGRpYWxvZyBkaXNtaXNzZWQnLCB7IGRpc3BsYXk6ICdzeXN0ZW0nIH0pXG4gIHVzZUtleWJpbmRpbmcoJ2hlbHA6ZGlzbWlzcycsIGNsb3NlLCB7IGNvbnRleHQ6ICdIZWxwJyB9KVxuICBjb25zdCBleGl0U3RhdGUgPSB1c2VFeGl0T25DdHJsQ0RXaXRoS2V5YmluZGluZ3MoY2xvc2UpXG4gIGNvbnN0IGRpc21pc3NTaG9ydGN1dCA9IHVzZVNob3J0Y3V0RGlzcGxheSgnaGVscDpkaXNtaXNzJywgJ0hlbHAnLCAnZXNjJylcblxuICBjb25zdCBidWlsdGluTmFtZXMgPSBidWlsdEluQ29tbWFuZE5hbWVzKClcbiAgbGV0IGJ1aWx0aW5Db21tYW5kcyA9IGNvbW1hbmRzLmZpbHRlcihcbiAgICBjbWQgPT4gYnVpbHRpbk5hbWVzLmhhcyhjbWQubmFtZSkgJiYgIWNtZC5pc0hpZGRlbixcbiAgKVxuICBsZXQgYW50T25seUNvbW1hbmRzOiBDb21tYW5kW10gPSBbXVxuXG4gIC8vIFdlIGhhdmUgdG8gZG8gdGhpcyBpbiBhbiBgaWZgIHRvIGhlbHAgdHJlZXNoYWtpbmdcbiAgaWYgKFwiZXh0ZXJuYWxcIiA9PT0gJ2FudCcpIHtcbiAgICBjb25zdCBpbnRlcm5hbE9ubHlOYW1lcyA9IG5ldyBTZXQoSU5URVJOQUxfT05MWV9DT01NQU5EUy5tYXAoXyA9PiBfLm5hbWUpKVxuICAgIGJ1aWx0aW5Db21tYW5kcyA9IGJ1aWx0aW5Db21tYW5kcy5maWx0ZXIoXG4gICAgICBjbWQgPT4gIWludGVybmFsT25seU5hbWVzLmhhcyhjbWQubmFtZSksXG4gICAgKVxuICAgIGFudE9ubHlDb21tYW5kcyA9IGNvbW1hbmRzLmZpbHRlcihcbiAgICAgIGNtZCA9PiBpbnRlcm5hbE9ubHlOYW1lcy5oYXMoY21kLm5hbWUpICYmICFjbWQuaXNIaWRkZW4sXG4gICAgKVxuICB9XG5cbiAgY29uc3QgY3VzdG9tQ29tbWFuZHMgPSBjb21tYW5kcy5maWx0ZXIoXG4gICAgY21kID0+ICFidWlsdGluTmFtZXMuaGFzKGNtZC5uYW1lKSAmJiAhY21kLmlzSGlkZGVuLFxuICApXG5cbiAgY29uc3QgdGFicyA9IFtcbiAgICA8VGFiIGtleT1cImdlbmVyYWxcIiB0aXRsZT1cImdlbmVyYWxcIj5cbiAgICAgIDxHZW5lcmFsIC8+XG4gICAgPC9UYWI+LFxuICBdXG5cbiAgdGFicy5wdXNoKFxuICAgIDxUYWIga2V5PVwiY29tbWFuZHNcIiB0aXRsZT1cImNvbW1hbmRzXCI+XG4gICAgICA8Q29tbWFuZHNcbiAgICAgICAgY29tbWFuZHM9e2J1aWx0aW5Db21tYW5kc31cbiAgICAgICAgbWF4SGVpZ2h0PXttYXhIZWlnaHR9XG4gICAgICAgIGNvbHVtbnM9e2NvbHVtbnN9XG4gICAgICAgIHRpdGxlPVwiQnJvd3NlIGRlZmF1bHQgY29tbWFuZHM6XCJcbiAgICAgICAgb25DYW5jZWw9e2Nsb3NlfVxuICAgICAgLz5cbiAgICA8L1RhYj4sXG4gIClcblxuICB0YWJzLnB1c2goXG4gICAgPFRhYiBrZXk9XCJjdXN0b21cIiB0aXRsZT1cImN1c3RvbS1jb21tYW5kc1wiPlxuICAgICAgPENvbW1hbmRzXG4gICAgICAgIGNvbW1hbmRzPXtjdXN0b21Db21tYW5kc31cbiAgICAgICAgbWF4SGVpZ2h0PXttYXhIZWlnaHR9XG4gICAgICAgIGNvbHVtbnM9e2NvbHVtbnN9XG4gICAgICAgIHRpdGxlPVwiQnJvd3NlIGN1c3RvbSBjb21tYW5kczpcIlxuICAgICAgICBlbXB0eU1lc3NhZ2U9XCJObyBjdXN0b20gY29tbWFuZHMgZm91bmRcIlxuICAgICAgICBvbkNhbmNlbD17Y2xvc2V9XG4gICAgICAvPlxuICAgIDwvVGFiPixcbiAgKVxuXG4gIGlmIChcImV4dGVybmFsXCIgPT09ICdhbnQnICYmIGFudE9ubHlDb21tYW5kcy5sZW5ndGggPiAwKSB7XG4gICAgdGFicy5wdXNoKFxuICAgICAgPFRhYiBrZXk9XCJhbnQtb25seVwiIHRpdGxlPVwiW2FudC1vbmx5XVwiPlxuICAgICAgICA8Q29tbWFuZHNcbiAgICAgICAgICBjb21tYW5kcz17YW50T25seUNvbW1hbmRzfVxuICAgICAgICAgIG1heEhlaWdodD17bWF4SGVpZ2h0fVxuICAgICAgICAgIGNvbHVtbnM9e2NvbHVtbnN9XG4gICAgICAgICAgdGl0bGU9XCJCcm93c2UgYW50LW9ubHkgY29tbWFuZHM6XCJcbiAgICAgICAgICBvbkNhbmNlbD17Y2xvc2V9XG4gICAgICAgIC8+XG4gICAgICA8L1RhYj4sXG4gICAgKVxuICB9XG5cbiAgcmV0dXJuIChcbiAgICA8Qm94IGZsZXhEaXJlY3Rpb249XCJjb2x1bW5cIiBoZWlnaHQ9e2luc2lkZU1vZGFsID8gdW5kZWZpbmVkIDogbWF4SGVpZ2h0fT5cbiAgICAgIDxQYW5lIGNvbG9yPVwicHJvZmVzc2lvbmFsQmx1ZVwiPlxuICAgICAgICA8VGFic1xuICAgICAgICAgIHRpdGxlPXtcbiAgICAgICAgICAgIFwiZXh0ZXJuYWxcIiA9PT0gJ2FudCdcbiAgICAgICAgICAgICAgPyAnL2hlbHAnXG4gICAgICAgICAgICAgIDogYENsYXVkZSBDb2RlIHYke01BQ1JPLlZFUlNJT059YFxuICAgICAgICAgIH1cbiAgICAgICAgICBjb2xvcj1cInByb2Zlc3Npb25hbEJsdWVcIlxuICAgICAgICAgIGRlZmF1bHRUYWI9XCJnZW5lcmFsXCJcbiAgICAgICAgPlxuICAgICAgICAgIHt0YWJzfVxuICAgICAgICA8L1RhYnM+XG4gICAgICAgIDxCb3ggbWFyZ2luVG9wPXsxfT5cbiAgICAgICAgICA8VGV4dD5cbiAgICAgICAgICAgIEZvciBtb3JlIGhlbHA6eycgJ31cbiAgICAgICAgICAgIDxMaW5rIHVybD1cImh0dHBzOi8vY29kZS5jbGF1ZGUuY29tL2RvY3MvZW4vb3ZlcnZpZXdcIiAvPlxuICAgICAgICAgIDwvVGV4dD5cbiAgICAgICAgPC9Cb3g+XG4gICAgICAgIDxCb3ggbWFyZ2luVG9wPXsxfT5cbiAgICAgICAgICA8VGV4dCBkaW1Db2xvcj5cbiAgICAgICAgICAgIHtleGl0U3RhdGUucGVuZGluZyA/IChcbiAgICAgICAgICAgICAgPD5QcmVzcyB7ZXhpdFN0YXRlLmtleU5hbWV9IGFnYWluIHRvIGV4aXQ8Lz5cbiAgICAgICAgICAgICkgOiAoXG4gICAgICAgICAgICAgIDxUZXh0IGl0YWxpYz57ZGlzbWlzc1Nob3J0Y3V0fSB0byBjYW5jZWw8L1RleHQ+XG4gICAgICAgICAgICApfVxuICAgICAgICAgIDwvVGV4dD5cbiAgICAgICAgPC9Cb3g+XG4gICAgICA8L1BhbmU+XG4gICAgPC9Cb3g+XG4gIClcbn1cbiJdLCJtYXBwaW5ncyI6IjtBQUFBLE9BQU8sS0FBS0EsS0FBSyxNQUFNLE9BQU87QUFDOUIsU0FBU0MsOEJBQThCLFFBQVEsNkNBQTZDO0FBQzVGLFNBQVNDLGtCQUFrQixRQUFRLHVDQUF1QztBQUMxRSxTQUNFQyxtQkFBbUIsRUFDbkIsS0FBS0MsT0FBTyxFQUNaLEtBQUtDLG9CQUFvQixFQUN6QkMsc0JBQXNCLFFBQ2pCLG1CQUFtQjtBQUMxQixTQUFTQyxnQkFBZ0IsUUFBUSwrQkFBK0I7QUFDaEUsU0FBU0MsZUFBZSxRQUFRLGdDQUFnQztBQUNoRSxTQUFTQyxHQUFHLEVBQUVDLElBQUksRUFBRUMsSUFBSSxRQUFRLGNBQWM7QUFDOUMsU0FBU0MsYUFBYSxRQUFRLG9DQUFvQztBQUNsRSxTQUFTQyxJQUFJLFFBQVEsMEJBQTBCO0FBQy9DLFNBQVNDLEdBQUcsRUFBRUMsSUFBSSxRQUFRLDBCQUEwQjtBQUNwRCxTQUFTQyxRQUFRLFFBQVEsZUFBZTtBQUN4QyxTQUFTQyxPQUFPLFFBQVEsY0FBYztBQUV0QyxLQUFLQyxLQUFLLEdBQUc7RUFDWEMsT0FBTyxFQUFFLENBQ1BDLE1BQWUsQ0FBUixFQUFFLE1BQU0sRUFDZkMsT0FBNEMsQ0FBcEMsRUFBRTtJQUFFQyxPQUFPLENBQUMsRUFBRWpCLG9CQUFvQjtFQUFDLENBQUMsRUFDNUMsR0FBRyxJQUFJO0VBQ1RrQixRQUFRLEVBQUVuQixPQUFPLEVBQUU7QUFDckIsQ0FBQztBQUVELE9BQU8sU0FBQW9CLE9BQUFDLEVBQUE7RUFBQSxNQUFBQyxDQUFBLEdBQUFDLEVBQUE7RUFBZ0I7SUFBQVIsT0FBQTtJQUFBSTtFQUFBLElBQUFFLEVBQTRCO0VBQ2pEO0lBQUFHLElBQUE7SUFBQUM7RUFBQSxJQUEwQnJCLGVBQWUsQ0FBQyxDQUFDO0VBQzNDLE1BQUFzQixTQUFBLEdBQWtCQyxJQUFJLENBQUFDLEtBQU0sQ0FBQ0osSUFBSSxHQUFHLENBQUMsQ0FBQztFQUl0QyxNQUFBSyxXQUFBLEdBQW9CMUIsZ0JBQWdCLENBQUMsQ0FBQztFQUFBLElBQUEyQixFQUFBO0VBQUEsSUFBQVIsQ0FBQSxRQUFBUCxPQUFBO0lBRXhCZSxFQUFBLEdBQUFBLENBQUEsS0FBTWYsT0FBTyxDQUFDLHVCQUF1QixFQUFFO01BQUFHLE9BQUEsRUFBVztJQUFTLENBQUMsQ0FBQztJQUFBSSxDQUFBLE1BQUFQLE9BQUE7SUFBQU8sQ0FBQSxNQUFBUSxFQUFBO0VBQUE7SUFBQUEsRUFBQSxHQUFBUixDQUFBO0VBQUE7RUFBM0UsTUFBQVMsS0FBQSxHQUFjRCxFQUE2RDtFQUFBLElBQUFFLEVBQUE7RUFBQSxJQUFBVixDQUFBLFFBQUFXLE1BQUEsQ0FBQUMsR0FBQTtJQUN0Q0YsRUFBQTtNQUFBRyxPQUFBLEVBQVc7SUFBTyxDQUFDO0lBQUFiLENBQUEsTUFBQVUsRUFBQTtFQUFBO0lBQUFBLEVBQUEsR0FBQVYsQ0FBQTtFQUFBO0VBQXhEZCxhQUFhLENBQUMsY0FBYyxFQUFFdUIsS0FBSyxFQUFFQyxFQUFtQixDQUFDO0VBQ3pELE1BQUFJLFNBQUEsR0FBa0J2Qyw4QkFBOEIsQ0FBQ2tDLEtBQUssQ0FBQztFQUN2RCxNQUFBTSxlQUFBLEdBQXdCdkMsa0JBQWtCLENBQUMsY0FBYyxFQUFFLE1BQU0sRUFBRSxLQUFLLENBQUM7RUFBQSxJQUFBd0MsZUFBQTtFQUFBLElBQUFDLGVBQUE7RUFBQSxJQUFBQyxFQUFBO0VBQUEsSUFBQWxCLENBQUEsUUFBQUgsUUFBQTtJQUV6RSxNQUFBc0IsWUFBQSxHQUFxQjFDLG1CQUFtQixDQUFDLENBQUM7SUFDMUN3QyxlQUFBLEdBQXNCcEIsUUFBUSxDQUFBdUIsTUFBTyxDQUNuQ0MsR0FBQSxJQUFPRixZQUFZLENBQUFHLEdBQUksQ0FBQ0QsR0FBRyxDQUFBRSxJQUFzQixDQUFDLElBQTNDLENBQStCRixHQUFHLENBQUFHLFFBQzNDLENBQUM7SUFBQSxJQUFBQyxFQUFBO0lBQUEsSUFBQXpCLENBQUEsUUFBQVcsTUFBQSxDQUFBQyxHQUFBO01BQ2dDYSxFQUFBLEtBQUU7TUFBQXpCLENBQUEsTUFBQXlCLEVBQUE7SUFBQTtNQUFBQSxFQUFBLEdBQUF6QixDQUFBO0lBQUE7SUFBbkNnQixlQUFBLEdBQWlDUyxFQUFFO0lBYVpQLEVBQUEsR0FBQXJCLFFBQVEsQ0FBQXVCLE1BQU8sQ0FDcENNLEtBQUEsSUFBTyxDQUFDUCxZQUFZLENBQUFHLEdBQUksQ0FBQ0QsS0FBRyxDQUFBRSxJQUFLLENBQWtCLElBQTVDLENBQWdDRixLQUFHLENBQUFHLFFBQzVDLENBQUM7SUFBQXhCLENBQUEsTUFBQUgsUUFBQTtJQUFBRyxDQUFBLE1BQUFnQixlQUFBO0lBQUFoQixDQUFBLE1BQUFpQixlQUFBO0lBQUFqQixDQUFBLE1BQUFrQixFQUFBO0VBQUE7SUFBQUYsZUFBQSxHQUFBaEIsQ0FBQTtJQUFBaUIsZUFBQSxHQUFBakIsQ0FBQTtJQUFBa0IsRUFBQSxHQUFBbEIsQ0FBQTtFQUFBO0VBRkQsTUFBQTJCLGNBQUEsR0FBdUJULEVBRXRCO0VBQUEsSUFBQU8sRUFBQTtFQUFBLElBQUF6QixDQUFBLFFBQUFXLE1BQUEsQ0FBQUMsR0FBQTtJQUdDYSxFQUFBLElBQUMsR0FBRyxDQUFLLEdBQVMsQ0FBVCxTQUFTLENBQU8sS0FBUyxDQUFULFNBQVMsQ0FDaEMsQ0FBQyxPQUFPLEdBQ1YsRUFGQyxHQUFHLENBRUU7SUFBQXpCLENBQUEsTUFBQXlCLEVBQUE7RUFBQTtJQUFBQSxFQUFBLEdBQUF6QixDQUFBO0VBQUE7RUFBQSxJQUFBNEIsSUFBQTtFQUFBLElBQUE1QixDQUFBLFFBQUFnQixlQUFBLElBQUFoQixDQUFBLFNBQUFpQixlQUFBLElBQUFqQixDQUFBLFNBQUFTLEtBQUEsSUFBQVQsQ0FBQSxTQUFBRyxPQUFBLElBQUFILENBQUEsU0FBQTJCLGNBQUEsSUFBQTNCLENBQUEsU0FBQUksU0FBQTtJQUhSd0IsSUFBQSxHQUFhLENBQ1hILEVBRU0sQ0FDUDtJQUFBLElBQUFJLEVBQUE7SUFBQSxJQUFBN0IsQ0FBQSxTQUFBaUIsZUFBQSxJQUFBakIsQ0FBQSxTQUFBUyxLQUFBLElBQUFULENBQUEsU0FBQUcsT0FBQSxJQUFBSCxDQUFBLFNBQUFJLFNBQUE7TUFHQ3lCLEVBQUEsSUFBQyxHQUFHLENBQUssR0FBVSxDQUFWLFVBQVUsQ0FBTyxLQUFVLENBQVYsVUFBVSxDQUNsQyxDQUFDLFFBQVEsQ0FDR1osUUFBZSxDQUFmQSxnQkFBYyxDQUFDLENBQ2RiLFNBQVMsQ0FBVEEsVUFBUSxDQUFDLENBQ1hELE9BQU8sQ0FBUEEsUUFBTSxDQUFDLENBQ1YsS0FBMEIsQ0FBMUIsMEJBQTBCLENBQ3RCTSxRQUFLLENBQUxBLE1BQUksQ0FBQyxHQUVuQixFQVJDLEdBQUcsQ0FRRTtNQUFBVCxDQUFBLE9BQUFpQixlQUFBO01BQUFqQixDQUFBLE9BQUFTLEtBQUE7TUFBQVQsQ0FBQSxPQUFBRyxPQUFBO01BQUFILENBQUEsT0FBQUksU0FBQTtNQUFBSixDQUFBLE9BQUE2QixFQUFBO0lBQUE7TUFBQUEsRUFBQSxHQUFBN0IsQ0FBQTtJQUFBO0lBVFI0QixJQUFJLENBQUFFLElBQUssQ0FDUEQsRUFTRixDQUFDO0lBQUEsSUFBQUUsRUFBQTtJQUFBLElBQUEvQixDQUFBLFNBQUFTLEtBQUEsSUFBQVQsQ0FBQSxTQUFBRyxPQUFBLElBQUFILENBQUEsU0FBQTJCLGNBQUEsSUFBQTNCLENBQUEsU0FBQUksU0FBQTtNQUdDMkIsRUFBQSxJQUFDLEdBQUcsQ0FBSyxHQUFRLENBQVIsUUFBUSxDQUFPLEtBQWlCLENBQWpCLGlCQUFpQixDQUN2QyxDQUFDLFFBQVEsQ0FDR0osUUFBYyxDQUFkQSxlQUFhLENBQUMsQ0FDYnZCLFNBQVMsQ0FBVEEsVUFBUSxDQUFDLENBQ1hELE9BQU8sQ0FBUEEsUUFBTSxDQUFDLENBQ1YsS0FBeUIsQ0FBekIseUJBQXlCLENBQ2xCLFlBQTBCLENBQTFCLDBCQUEwQixDQUM3Qk0sUUFBSyxDQUFMQSxNQUFJLENBQUMsR0FFbkIsRUFUQyxHQUFHLENBU0U7TUFBQVQsQ0FBQSxPQUFBUyxLQUFBO01BQUFULENBQUEsT0FBQUcsT0FBQTtNQUFBSCxDQUFBLE9BQUEyQixjQUFBO01BQUEzQixDQUFBLE9BQUFJLFNBQUE7TUFBQUosQ0FBQSxPQUFBK0IsRUFBQTtJQUFBO01BQUFBLEVBQUEsR0FBQS9CLENBQUE7SUFBQTtJQVZSNEIsSUFBSSxDQUFBRSxJQUFLLENBQ1BDLEVBVUYsQ0FBQztJQUVELElBQUksS0FBa0QsSUFBMUJmLGVBQWUsQ0FBQWdCLE1BQU8sR0FBRyxDQUFDO01BQUEsSUFBQUMsRUFBQTtNQUFBLElBQUFqQyxDQUFBLFNBQUFnQixlQUFBLElBQUFoQixDQUFBLFNBQUFTLEtBQUEsSUFBQVQsQ0FBQSxTQUFBRyxPQUFBLElBQUFILENBQUEsU0FBQUksU0FBQTtRQUVsRDZCLEVBQUEsSUFBQyxHQUFHLENBQUssR0FBVSxDQUFWLFVBQVUsQ0FBTyxLQUFZLENBQVosWUFBWSxDQUNwQyxDQUFDLFFBQVEsQ0FDR2pCLFFBQWUsQ0FBZkEsZ0JBQWMsQ0FBQyxDQUNkWixTQUFTLENBQVRBLFVBQVEsQ0FBQyxDQUNYRCxPQUFPLENBQVBBLFFBQU0sQ0FBQyxDQUNWLEtBQTJCLENBQTNCLDJCQUEyQixDQUN2Qk0sUUFBSyxDQUFMQSxNQUFJLENBQUMsR0FFbkIsRUFSQyxHQUFHLENBUUU7UUFBQVQsQ0FBQSxPQUFBZ0IsZUFBQTtRQUFBaEIsQ0FBQSxPQUFBUyxLQUFBO1FBQUFULENBQUEsT0FBQUcsT0FBQTtRQUFBSCxDQUFBLE9BQUFJLFNBQUE7UUFBQUosQ0FBQSxPQUFBaUMsRUFBQTtNQUFBO1FBQUFBLEVBQUEsR0FBQWpDLENBQUE7TUFBQTtNQVRSNEIsSUFBSSxDQUFBRSxJQUFLLENBQ1BHLEVBU0YsQ0FBQztJQUFBO0lBQ0ZqQyxDQUFBLE1BQUFnQixlQUFBO0lBQUFoQixDQUFBLE9BQUFpQixlQUFBO0lBQUFqQixDQUFBLE9BQUFTLEtBQUE7SUFBQVQsQ0FBQSxPQUFBRyxPQUFBO0lBQUFILENBQUEsT0FBQTJCLGNBQUE7SUFBQTNCLENBQUEsT0FBQUksU0FBQTtJQUFBSixDQUFBLE9BQUE0QixJQUFBO0VBQUE7SUFBQUEsSUFBQSxHQUFBNUIsQ0FBQTtFQUFBO0VBR3FDLE1BQUE2QixFQUFBLEdBQUF0QixXQUFXLEdBQVgyQixTQUFtQyxHQUFuQzlCLFNBQW1DO0VBQUEsSUFBQTJCLEVBQUE7RUFBQSxJQUFBL0IsQ0FBQSxTQUFBNEIsSUFBQTtJQUVuRUcsRUFBQSxJQUFDLElBQUksQ0FFRCxLQUVtQyxDQUZuQyxNQUFvQixHQUFwQixPQUVtQyxHQUZuQyxnQkFFb0JJLEtBQUssQ0FBQUMsT0FBUSxFQUFDLENBQUMsQ0FFL0IsS0FBa0IsQ0FBbEIsa0JBQWtCLENBQ2IsVUFBUyxDQUFULFNBQVMsQ0FFbkJSLEtBQUcsQ0FDTixFQVZDLElBQUksQ0FVRTtJQUFBNUIsQ0FBQSxPQUFBNEIsSUFBQTtJQUFBNUIsQ0FBQSxPQUFBK0IsRUFBQTtFQUFBO0lBQUFBLEVBQUEsR0FBQS9CLENBQUE7RUFBQTtFQUFBLElBQUFpQyxFQUFBO0VBQUEsSUFBQWpDLENBQUEsU0FBQVcsTUFBQSxDQUFBQyxHQUFBO0lBQ1BxQixFQUFBLElBQUMsR0FBRyxDQUFZLFNBQUMsQ0FBRCxHQUFDLENBQ2YsQ0FBQyxJQUFJLENBQUMsY0FDVyxJQUFFLENBQ2pCLENBQUMsSUFBSSxDQUFLLEdBQTBDLENBQTFDLDBDQUEwQyxHQUN0RCxFQUhDLElBQUksQ0FJUCxFQUxDLEdBQUcsQ0FLRTtJQUFBakMsQ0FBQSxPQUFBaUMsRUFBQTtFQUFBO0lBQUFBLEVBQUEsR0FBQWpDLENBQUE7RUFBQTtFQUFBLElBQUFxQyxFQUFBO0VBQUEsSUFBQXJDLENBQUEsU0FBQWUsZUFBQSxJQUFBZixDQUFBLFNBQUFjLFNBQUEsQ0FBQXdCLE9BQUEsSUFBQXRDLENBQUEsU0FBQWMsU0FBQSxDQUFBeUIsT0FBQTtJQUNORixFQUFBLElBQUMsR0FBRyxDQUFZLFNBQUMsQ0FBRCxHQUFDLENBQ2YsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFSLEtBQU8sQ0FBQyxDQUNYLENBQUF2QixTQUFTLENBQUF5QixPQUlULEdBSkEsRUFDRyxNQUFPLENBQUF6QixTQUFTLENBQUF3QixPQUFPLENBQUUsY0FBYyxHQUcxQyxHQURDLENBQUMsSUFBSSxDQUFDLE1BQU0sQ0FBTixLQUFLLENBQUMsQ0FBRXZCLGdCQUFjLENBQUUsVUFBVSxFQUF2QyxJQUFJLENBQ1AsQ0FDRixFQU5DLElBQUksQ0FPUCxFQVJDLEdBQUcsQ0FRRTtJQUFBZixDQUFBLE9BQUFlLGVBQUE7SUFBQWYsQ0FBQSxPQUFBYyxTQUFBLENBQUF3QixPQUFBO0lBQUF0QyxDQUFBLE9BQUFjLFNBQUEsQ0FBQXlCLE9BQUE7SUFBQXZDLENBQUEsT0FBQXFDLEVBQUE7RUFBQTtJQUFBQSxFQUFBLEdBQUFyQyxDQUFBO0VBQUE7RUFBQSxJQUFBd0MsRUFBQTtFQUFBLElBQUF4QyxDQUFBLFNBQUErQixFQUFBLElBQUEvQixDQUFBLFNBQUFxQyxFQUFBO0lBMUJSRyxFQUFBLElBQUMsSUFBSSxDQUFPLEtBQWtCLENBQWxCLGtCQUFrQixDQUM1QixDQUFBVCxFQVVNLENBQ04sQ0FBQUUsRUFLSyxDQUNMLENBQUFJLEVBUUssQ0FDUCxFQTNCQyxJQUFJLENBMkJFO0lBQUFyQyxDQUFBLE9BQUErQixFQUFBO0lBQUEvQixDQUFBLE9BQUFxQyxFQUFBO0lBQUFyQyxDQUFBLE9BQUF3QyxFQUFBO0VBQUE7SUFBQUEsRUFBQSxHQUFBeEMsQ0FBQTtFQUFBO0VBQUEsSUFBQXlDLEdBQUE7RUFBQSxJQUFBekMsQ0FBQSxTQUFBNkIsRUFBQSxJQUFBN0IsQ0FBQSxTQUFBd0MsRUFBQTtJQTVCVEMsR0FBQSxJQUFDLEdBQUcsQ0FBZSxhQUFRLENBQVIsUUFBUSxDQUFTLE1BQW1DLENBQW5DLENBQUFaLEVBQWtDLENBQUMsQ0FDckUsQ0FBQVcsRUEyQk0sQ0FDUixFQTdCQyxHQUFHLENBNkJFO0lBQUF4QyxDQUFBLE9BQUE2QixFQUFBO0lBQUE3QixDQUFBLE9BQUF3QyxFQUFBO0lBQUF4QyxDQUFBLE9BQUF5QyxHQUFBO0VBQUE7SUFBQUEsR0FBQSxHQUFBekMsQ0FBQTtFQUFBO0VBQUEsT0E3Qk55QyxHQTZCTTtBQUFBIiwiaWdub3JlTGlzdCI6W119
